# Generated by Django 4.2.6 on 2023-10-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password_hash', models.CharField(max_length=128)),
                ('avatar_url', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friendship', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_друга', to='Telgis.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_пользователя', to='Telgis.users')),
            ],
        ),
    ]
