# Generated by Django 4.2.6 on 2023-10-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telgis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(max_length=30)),
                ('chat_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Telgis.chats')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Telgis.users')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telgis.users')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMembers',
            fields=[
                ('chat_member', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telgis.chats')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telgis.users')),
            ],
        ),
    ]
